---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: radicale-tls
  namespace: radicale
spec:
  secretName: radicale-tls
  issuerRef:
    name: homelab-ca-issuer
    kind: ClusterIssuer
  dnsNames:
    - radicale.tail060ef.ts.net
  duration: 8760h  # 1 year
  renewBefore: 720h  # 30 days
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: radicale
data:
  default.conf: |
    server {
        listen 443 ssl;
        server_name radicale.tail060ef.ts.net;

        ssl_certificate /etc/nginx/ssl/tls.crt;
        ssl_certificate_key /etc/nginx/ssl/tls.key;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;

        location / {
            proxy_pass http://localhost:5232;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radicale
  namespace: radicale
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: radicale
  template:
    metadata:
      labels:
        app: radicale
    spec:
      containers:
      - name: radicale
        image: tomsquest/docker-radicale:latest
        ports:
        - containerPort: 5232
        env:
        - name: TAKE_FILE_OWNERSHIP
          value: "false"
        volumeMounts:
        - name: radicale-data
          mountPath: /data
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 443
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
        - name: tls-cert
          mountPath: /etc/nginx/ssl
          readOnly: true
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      volumes:
      - name: radicale-data
        persistentVolumeClaim:
          claimName: radicale-data
      - name: nginx-config
        configMap:
          name: nginx-config
      - name: tls-cert
        secret:
          secretName: radicale-tls
---
apiVersion: v1
kind: Service
metadata:
  name: radicale
  namespace: radicale
  annotations:
    tailscale.com/hostname: "radicale"
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  selector:
    app: radicale
  ports:
  - port: 443
    targetPort: 443
    name: https
