---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: firefly-upload
  namespace: firefly-iii
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: firefly-iii
  namespace: firefly-iii
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: firefly-iii
  template:
    metadata:
      labels:
        app: firefly-iii
    spec:
      containers:
      - name: firefly-iii
        image: fireflyiii/core:latest
        ports:
        - containerPort: 8080
        env:
        - name: APP_ENV
          value: "production"
        - name: APP_URL
          value: "http://firefly.tail060ef.ts.net"
        - name: TRUSTED_PROXIES
          value: "**"
        - name: LOG_CHANNEL
          value: "stdout"
        - name: APP_LOG_LEVEL
          value: "info"
        - name: AUDIT_LOG_LEVEL
          value: "info"
        envFrom:
        - secretRef:
            name: firefly-secret
        volumeMounts:
        - name: firefly-upload
          mountPath: /var/www/html/storage/upload
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: firefly-upload
        persistentVolumeClaim:
          claimName: firefly-upload
---
apiVersion: v1
kind: Service
metadata:
  name: firefly-iii
  namespace: firefly-iii
  annotations:
    tailscale.com/hostname: "firefly"
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  selector:
    app: firefly-iii
  ports:
  - port: 80
    targetPort: 8080
    name: http
