---
# PVC is now defined in postgres-pv.yml
# This ensures the same NFS path is used across cluster recreations
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: firefly-iii
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        envFrom:
        - secretRef:
            name: postgres-secret
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-data
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: firefly-iii
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
  clusterIP: None
