---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: firefly-postgres-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain  # Keep data even if PVC is deleted
  storageClassName: ""  # Empty to prevent dynamic provisioning
  nfs:
    server: 192.168.1.150
    path: /ZFS01/nfs-storage/firefly-postgres
  mountOptions:
    - hard
    - nfsvers=4.1

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: firefly-iii
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""  # Must match PV
  volumeName: firefly-postgres-pv  # Bind to specific PV
