---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  namespace: qbittorrent
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      containers:
      - name: qbittorrent
        image: linuxserver/qbittorrent:latest
        env:
        - name: PUID
          value: "0"
        - name: PGID
          value: "0"
        - name: TZ
          value: "Europe/Vilnius"
        - name: WEBUI_PORT
          value: "8080"
        ports:
        - containerPort: 8080
          protocol: TCP
          name: webui
        - containerPort: 6881
          protocol: TCP
          name: torrent-tcp
        - containerPort: 6881
          protocol: UDP
          name: torrent-udp
        volumeMounts:
        - name: config
          mountPath: /config
        - name: downloads
          mountPath: /downloads
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: qbittorrent-config
      - name: downloads
        persistentVolumeClaim:
          claimName: qbittorrent-downloads
---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent-webui
  namespace: qbittorrent
  annotations:
    tailscale.com/hostname: "qbittorrent"
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  selector:
    app: qbittorrent
  ports:
  - port: 80
    targetPort: 8080
    name: http
---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent-torrent
  namespace: qbittorrent
spec:
  type: NodePort
  selector:
    app: qbittorrent
  ports:
  - port: 6881
    targetPort: 6881
    nodePort: 30681
    protocol: TCP
    name: torrent-tcp
  - port: 6881
    targetPort: 6881
    nodePort: 30681
    protocol: UDP
    name: torrent-udp
