---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minidlna-media-pv
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 192.168.1.150
    path: /ZFS01/nfs-storage/media
  mountOptions:
    - hard
    - nfsvers=4.1

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minidlna-media
  namespace: minidlna
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: ""
  volumeName: minidlna-media-pv
